export const GET_FORM_DATA = 'GET_FORM_DATA';
export const SEND_FORM_DATA = 'SEND_FORM_DATA';
export const SET_INPUT_VALUE = 'SET_INPUT_VALUE';
export const SET_SENDING_STATUS = 'SET_SENDING_STATUS';
export const SET_SEND_NOTIFICATION_STATUS = 'SET_SEND_NOTIFICATION_STATUS';

